package presentation

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"

	"github.com/ddd-todo/project-backend/graph"
	"github.com/ddd-todo/project-backend/graph/graphmodel"
)

// TodoMutation is the resolver for the TodoMutation field.
func (r *mutationResolver) TodoMutation(ctx context.Context) (*graphmodel.TodoMutation, error) {
	return &graphmodel.TodoMutation{}, nil
}

// UserMutation is the resolver for the UserMutation field.
func (r *mutationResolver) UserMutation(ctx context.Context) (*graphmodel.UserMutation, error) {
	return &graphmodel.UserMutation{}, nil
}

// TodoQuery is the resolver for the TodoQuery field.
func (r *queryResolver) TodoQuery(ctx context.Context) (*graphmodel.TodoQuery, error) {
	return &graphmodel.TodoQuery{}, nil
}

// UserQuery is the resolver for the UserQuery field.
func (r *queryResolver) UserQuery(ctx context.Context) (*graphmodel.UserQuery, error) {
	return &graphmodel.UserQuery{}, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
