package controller

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/ddd-todo/project-backend/graph"
	"github.com/ddd-todo/project-backend/graph/graphmodel"
	gqlport "github.com/ddd-todo/project-backend/port/gqlport/todo"
)

// Create is the resolver for the Create field.
func (r *todoMutationResolver) Create(ctx context.Context, obj *graphmodel.TodoMutation, input graphmodel.TodoCreateInput) (bool, error) {
	dtoInput := gqlport.ToDtoCreateTodoInput(input)
	return r.sevice.TodoUsecase.CreateTodo(ctx, dtoInput)
}

// Update is the resolver for the Update field.
func (r *todoMutationResolver) Update(ctx context.Context, obj *graphmodel.TodoMutation, input graphmodel.TodoUpdateInput) (bool, error) {
	dtoInput := gqlport.ToDtoUpdateTodoInput(input)
	return r.sevice.TodoUsecase.UpdateTodoDetail(ctx, dtoInput)
}

// Delete is the resolver for the Delete field.
func (r *todoMutationResolver) Delete(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	dtoInput := gqlport.ToDtoTodoMutationInput(id)
	return r.sevice.TodoUsecase.DeleteTodo(ctx, dtoInput)
}

// Start is the resolver for the Start field.
func (r *todoMutationResolver) Start(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	dtoInput := gqlport.ToDtoTodoMutationInput(id)
	return r.sevice.TodoUsecase.StartTodo(ctx, dtoInput)
}

// Suspend is the resolver for the Suspend field.
func (r *todoMutationResolver) Suspend(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	dtoInput := gqlport.ToDtoTodoMutationInput(id)
	return r.sevice.TodoUsecase.SuspendTodo(ctx, dtoInput)
}

// Complete is the resolver for the Complete field.
func (r *todoMutationResolver) Complete(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	dtoInput := gqlport.ToDtoTodoMutationInput(id)
	return r.sevice.TodoUsecase.CompleteTodo(ctx, dtoInput)
}

// Reopen is the resolver for the Reopen field.
func (r *todoMutationResolver) Reopen(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	dtoInput := gqlport.ToDtoTodoMutationInput(id)
	return r.sevice.TodoUsecase.ReopenTodo(ctx, dtoInput)
}

// GetByID is the resolver for the GetByID field.
func (r *todoQueryResolver) GetByID(ctx context.Context, obj *graphmodel.TodoQuery, id string) (*graphmodel.Todo, error) {
	dtoInput := gqlport.ToDtoGetTodoDetailInput(id)
	dtoOutput, err := r.sevice.TodoUsecase.GetTodoDetail(ctx, dtoInput)
	if err != nil {
		return nil, err
	}

	return gqlport.ToGqlTodo(dtoOutput), nil
}

// List is the resolver for the List field.
func (r *todoQueryResolver) List(ctx context.Context, obj *graphmodel.TodoQuery, filter graphmodel.TodoFilter, pageInput graphmodel.PageInput) (*graphmodel.TodoConnection, error) {
	dtoFilter := gqlport.ToDtoTodoFilterInput(filter)
	dtoPageInput := gqlport.ToDtoTodoPageInput(pageInput)
	dtoOutput, err := r.sevice.TodoUsecase.ListTodos(ctx, dtoFilter, dtoPageInput)
	if err != nil {
		return nil, err
	}

	return gqlport.ToGqlTodoConnection(dtoOutput), nil
}

// TodoMutation returns graph.TodoMutationResolver implementation.
func (r *Resolver) TodoMutation() graph.TodoMutationResolver { return &todoMutationResolver{r} }

// TodoQuery returns graph.TodoQueryResolver implementation.
func (r *Resolver) TodoQuery() graph.TodoQueryResolver { return &todoQueryResolver{r} }

type todoMutationResolver struct{ *Resolver }
type todoQueryResolver struct{ *Resolver }
