package controller

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/ddd-todo/project-backend/graph"
	"github.com/ddd-todo/project-backend/graph/graphmodel"
	gqlport "github.com/ddd-todo/project-backend/port/gqlport/user"
)

// Create is the resolver for the Create field.
func (r *userMutationResolver) Create(ctx context.Context, obj *graphmodel.UserMutation, input graphmodel.UserCreateInput) (bool, error) {
	dtoInput := gqlport.ToDtoUserRegisterInput(input)
	return r.sevice.UserUsecase.Register(ctx, dtoInput)
}

// Login is the resolver for the Login field.
func (r *userMutationResolver) Login(ctx context.Context, obj *graphmodel.UserMutation, input graphmodel.LoginInput) (*graphmodel.LoginResponse, error) {
	dtoInput := gqlport.ToDtoUserLoginInput(input)
	dtoOutput, err := r.sevice.UserUsecase.Login(ctx, dtoInput)
	if err != nil {
		return nil, err
	}

	return gqlport.ToGqlLoginResponse(dtoOutput), nil
}

// Delete is the resolver for the Delete field.
func (r *userMutationResolver) Delete(ctx context.Context, obj *graphmodel.UserMutation, id string) (bool, error) {
	dtoInput := gqlport.ToDtoUserDeleteInput(id)
	return r.sevice.UserUsecase.DeleteUser(ctx, dtoInput)
}

// UpdateUserProfile is the resolver for the UpdateUserProfile field.
func (r *userMutationResolver) UpdateUserProfile(ctx context.Context, obj *graphmodel.UserMutation, id string, name string) (bool, error) {
	dtoInput := gqlport.ToDtoUserUpdateInput(id, name)
	return r.sevice.UserUsecase.UpdateUserProfile(ctx, dtoInput)
}

// UpdateUserEmail is the resolver for the UpdateUserEmail field.
func (r *userMutationResolver) UpdateUserEmail(ctx context.Context, obj *graphmodel.UserMutation, id string, email string) (bool, error) {
	dtoInput := gqlport.ToDtoUserUpdateInput(id, email)
	return r.sevice.UserUsecase.UpdateUserEmail(ctx, dtoInput)
}

// UpdateUserPassword is the resolver for the UpdateUserPassword field.
func (r *userMutationResolver) UpdateUserPassword(ctx context.Context, obj *graphmodel.UserMutation, id string, password string) (bool, error) {
	dtoInput := gqlport.ToDtoUserUpdateInput(id, password)
	return r.sevice.UserUsecase.UpdateUserPassword(ctx, dtoInput)
}

// GetByID is the resolver for the GetByID field.
func (r *userQueryResolver) GetByID(ctx context.Context, obj *graphmodel.UserQuery, id string) (*graphmodel.User, error) {
	dtoInput := gqlport.ToDtoGetUserByIDInput(id)
	dtoOutput, err := r.sevice.UserUsecase.GetUserByID(ctx, dtoInput)
	if err != nil {
		return nil, err
	}

	gqlUser := gqlport.ToGqlUser(dtoOutput)

	return &gqlUser, nil
}

// UserMutation returns graph.UserMutationResolver implementation.
func (r *Resolver) UserMutation() graph.UserMutationResolver { return &userMutationResolver{r} }

// UserQuery returns graph.UserQueryResolver implementation.
func (r *Resolver) UserQuery() graph.UserQueryResolver { return &userQueryResolver{r} }

type userMutationResolver struct{ *Resolver }
type userQueryResolver struct{ *Resolver }
