package presentation

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/ddd-todo/project-backend/graph"
	"github.com/ddd-todo/project-backend/graph/graphmodel"
)

// Create is the resolver for the Create field.
func (r *todoMutationResolver) Create(ctx context.Context, obj *graphmodel.TodoMutation, input graphmodel.TodoCreateInput) (bool, error) {
	return false, nil
}

// Update is the resolver for the Update field.
func (r *todoMutationResolver) Update(ctx context.Context, obj *graphmodel.TodoMutation, input graphmodel.TodoUpdateInput) (bool, error) {
	return false, nil
}

// Delete is the resolver for the Delete field.
func (r *todoMutationResolver) Delete(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	return false, nil
}

// Start is the resolver for the Start field.
func (r *todoMutationResolver) Start(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	return false, nil
}

// Suspend is the resolver for the Suspend field.
func (r *todoMutationResolver) Suspend(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	return false, nil
}

// Complete is the resolver for the Complete field.
func (r *todoMutationResolver) Complete(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	return false, nil
}

// Reopen is the resolver for the Reopen field.
func (r *todoMutationResolver) Reopen(ctx context.Context, obj *graphmodel.TodoMutation, id string) (bool, error) {
	return false, nil
}

// GetByID is the resolver for the GetByID field.
func (r *todoQueryResolver) GetByID(ctx context.Context, obj *graphmodel.TodoQuery, id string) (*graphmodel.Todo, error) {
	return nil, nil
}

// List is the resolver for the List field.
func (r *todoQueryResolver) List(ctx context.Context, obj *graphmodel.TodoQuery, filter graphmodel.TodoFilter, pageInput graphmodel.PageInput) (*graphmodel.TodoConnection, error) {
	return nil, nil
}

// TodoMutation returns graph.TodoMutationResolver implementation.
func (r *Resolver) TodoMutation() graph.TodoMutationResolver { return &todoMutationResolver{r} }

// TodoQuery returns graph.TodoQueryResolver implementation.
func (r *Resolver) TodoQuery() graph.TodoQueryResolver { return &todoQueryResolver{r} }

type todoMutationResolver struct{ *Resolver }
type todoQueryResolver struct{ *Resolver }
