package presentation

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/ddd-todo/project-backend/graph"
	"github.com/ddd-todo/project-backend/graph/graphmodel"
)

// Create is the resolver for the Create field.
func (r *userMutationResolver) Create(ctx context.Context, obj *graphmodel.UserMutation, input graphmodel.UserCreateInput) (bool, error) {
	return false, nil
}

// Login is the resolver for the Login field.
func (r *userMutationResolver) Login(ctx context.Context, obj *graphmodel.UserMutation, input graphmodel.LoginInput) (*graphmodel.LoginResponse, error) {
	return nil, nil
}

// Delete is the resolver for the Delete field.
func (r *userMutationResolver) Delete(ctx context.Context, obj *graphmodel.UserMutation, id string) (bool, error) {
	return false, nil
}

// UpdateUserProfile is the resolver for the UpdateUserProfile field.
func (r *userMutationResolver) UpdateUserProfile(ctx context.Context, obj *graphmodel.UserMutation, id string, name string) (bool, error) {
	return false, nil
}

// UpdateUserEmail is the resolver for the UpdateUserEmail field.
func (r *userMutationResolver) UpdateUserEmail(ctx context.Context, obj *graphmodel.UserMutation, id string, email string) (bool, error) {
	return false, nil
}

// UpdateUserPassword is the resolver for the UpdateUserPassword field.
func (r *userMutationResolver) UpdateUserPassword(ctx context.Context, obj *graphmodel.UserMutation, id string, password string) (bool, error) {
	return false, nil
}

// GetByID is the resolver for the GetByID field.
func (r *userQueryResolver) GetByID(ctx context.Context, obj *graphmodel.UserQuery, id string) (*graphmodel.User, error) {
	return nil, nil
}

// UserMutation returns graph.UserMutationResolver implementation.
func (r *Resolver) UserMutation() graph.UserMutationResolver { return &userMutationResolver{r} }

// UserQuery returns graph.UserQueryResolver implementation.
func (r *Resolver) UserQuery() graph.UserQueryResolver { return &userQueryResolver{r} }

type userMutationResolver struct{ *Resolver }
type userQueryResolver struct{ *Resolver }
