// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphmodel

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type PageInput struct {
	Limit         int           `json:"limit"`
	Offset        int           `json:"offset"`
	SortKey       *string       `json:"sortKey,omitempty"`
	SortDirection SortDirection `json:"sortDirection"`
}

type PagingInfo struct {
	TotalCount      int  `json:"totalCount"`
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
	Offset          int  `json:"offset"`
	Limit           int  `json:"limit"`
}

type Query struct {
}

type Todo struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Status      string     `json:"status"`
	Deadline    *time.Time `json:"deadline,omitempty"`
	Priority    *string    `json:"priority,omitempty"`
	UserID      string     `json:"userId"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

type TodoConnection struct {
	Items      []*Todo     `json:"items"`
	PagingInfo *PagingInfo `json:"pagingInfo"`
}

type TodoCreateInput struct {
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Deadline    *time.Time `json:"deadline,omitempty"`
	Priority    *string    `json:"priority,omitempty"`
	UserID      string     `json:"userId"`
}

type TodoFilter struct {
	Keyword        *string    `json:"keyword,omitempty"`
	Status         *string    `json:"status,omitempty"`
	Priority       *string    `json:"priority,omitempty"`
	DeadlineBefore *time.Time `json:"deadlineBefore,omitempty"`
	DeadlineAfter  *time.Time `json:"deadlineAfter,omitempty"`
	UserID         *string    `json:"userId,omitempty"`
}

type TodoMutation struct {
	Create   bool `json:"Create"`
	Update   bool `json:"Update"`
	Delete   bool `json:"Delete"`
	Start    bool `json:"Start"`
	Suspend  bool `json:"Suspend"`
	Complete bool `json:"Complete"`
	Reopen   bool `json:"Reopen"`
}

type TodoQuery struct {
	GetByID *Todo           `json:"GetByID,omitempty"`
	List    *TodoConnection `json:"List"`
}

type TodoUpdateInput struct {
	ID          string     `json:"id"`
	Title       *string    `json:"title,omitempty"`
	Description *string    `json:"description,omitempty"`
	Deadline    *time.Time `json:"deadline,omitempty"`
	Priority    *string    `json:"priority,omitempty"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type UserCreateInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserMutation struct {
	Create             bool           `json:"Create"`
	Login              *LoginResponse `json:"Login"`
	Delete             bool           `json:"Delete"`
	UpdateUserProfile  bool           `json:"UpdateUserProfile"`
	UpdateUserEmail    bool           `json:"UpdateUserEmail"`
	UpdateUserPassword bool           `json:"UpdateUserPassword"`
}

type UserQuery struct {
	GetByID *User `json:"GetByID,omitempty"`
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
