CREATE TABLE todos (
    id CHAR(36) PRIMARY KEY NOT NULL,
    title VARCHAR(64) NOT NULL,
    description TEXT,
    status VARCHAR(10) NOT NULL,
    deadline DATETIME,
    priority VARCHAR(10),
    user_id CHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);